apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    isDefault: true
    url: http://prometheus:9090
    jsonData:
      timeInterval: 15s
      exemplarTraceIdDestinations:
        - name: Trace ID
          url: http://jaeger:16686/search?service=claude-projects-api&tags=%7B"trace_id"%3A"$${__value.raw}"%7D
